name: Publish Release

on:
    workflow_dispatch:
        push:
            branches: [main]
            paths-ignore:
                - .github/workflows/*

permissions:
    contents: write

jobs:
    publish:
        runs-on: ubuntu-latest
        env:
            python_ver: 3.8

        steps:
            - uses: actions/checkout@v3
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
            - name: get version
              id: version
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'plugin.json'
                  prop_path: 'Version'
            - run: echo ${{steps.version.outputs.prop}}
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r ./requirements.txt -t ./lib
                  zip -r Flow.Launcher.Plugin.AudioEnvironments-${{steps.version.outputs.prop}}.zip . -x '*.git*'
            - name: Publish
              uses: softprops/action-gh-release@v1
              with:
                  files: 'Flow.Launcher.Plugin.AudioEnvironments-${{steps.version.outputs.prop}}.zip'
                  tag_name: 'v${{steps.version.outputs.prop}}'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
